/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");

  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";

  btn.style.position = "fixed";
  btn.style.top = "20px";
  btn.style.right = "20px";
  btn.style.zIndex = "9999";

  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });

  document.body.appendChild(btn);
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();

  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
    audio.volume = 0;
  }

  createMusicToggle(audio);

  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) return;
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  // 🔥 ENTER EXPERIENCE overlay
  createEnterExperience(audio, rendered);
});

// ── ENTER EXPERIENCE ─────────────────────────────────────────────
function createEnterExperience(audio, rendered) {
  const overlay = document.createElement("div");

  overlay.style.position = "fixed";
  overlay.style.top = "0";
  overlay.style.left = "0";
  overlay.style.width = "100%";
  overlay.style.height = "100%";
  overlay.style.background = "linear-gradient(135deg, #0f172a, #1e293b)";
  overlay.style.display = "flex";
  overlay.style.flexDirection = "column";
  overlay.style.alignItems = "center";
  overlay.style.justifyContent = "center";
  overlay.style.zIndex = "10000";
  overlay.style.color = "#fff";
  overlay.style.textAlign = "center";

  const title = document.createElement("h1");
  title.textContent = "Welcome";
  title.style.marginBottom = "10px";

  const subtitle = document.createElement("p");
  subtitle.textContent = "A small experience awaits you ✨";
  subtitle.style.marginBottom = "30px";
  subtitle.style.opacity = "0.8";

  const btn = document.createElement("button");
  btn.textContent = "Enter Experience";
  btn.style.fontSize = "18px";
  btn.style.padding = "15px 30px";
  btn.style.border = "none";
  btn.style.borderRadius = "12px";
  btn.style.background = "#15a1ed";
  btn.style.color = "#fff";
  btn.style.cursor = "pointer";
  btn.style.transition = "0.3s";

  btn.onmouseenter = () => (btn.style.transform = "scale(1.05)");
  btn.onmouseleave = () => (btn.style.transform = "scale(1)");

  btn.addEventListener("click", () => {
    if (audio) {
      audio.play().then(() => {
        fadeInAudio(audio, 0.8, 1500);
      }).catch(() => {});
    }

    overlay.style.opacity = "0";
    overlay.style.transition = "opacity 0.8s ease";

    setTimeout(() => {
      overlay.remove();
      buildTimeline(audio, rendered);
    }, 800);
  });

  overlay.appendChild(title);
  overlay.appendChild(subtitle);
  overlay.appendChild(btn);
  document.body.appendChild(overlay);
}

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(audio, rendered) {
  const tl = gsap.timeline();

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    comp.animate(tl, el, CONFIG);

    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  deferredExits.forEach((fn) => fn());

  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => {
      // Restart the timeline
      tl.restart();
      // Restart and play the audio
      if (audio) {
        audio.currentTime = 0;
        audio.play().then(() => {
          fadeInAudio(audio, 0.8, 1500);
        }).catch(() => {});
      }
    });
  }
}

// ── Music Helpers ────────────────────────────────────────────────
function fadeInAudio(audio, targetVolume = 1, duration = 1000) {
  const steps = 20;
  const stepTime = duration / steps;
  let currentStep = 0;

  const fade = setInterval(() => {
    currentStep++;
    audio.volume = Math.min(targetVolume, (currentStep / steps) * targetVolume);
    if (currentStep >= steps) clearInterval(fade);
  }, stepTime);
}

function createMusicToggle(audio) {
  if (!audio) return;

  const btn = document.createElement("button");
  btn.id = "music-toggle";
  btn.textContent = "🔊";

  btn.style.position = "fixed";
  btn.style.bottom = "20px";
  btn.style.right = "20px";
  btn.style.zIndex = "9999";

  btn.addEventListener("click", () => {
    if (audio.paused) {
      audio.play().then(() => {
        fadeInAudio(audio, 0.8, 800);
        btn.textContent = "🔊";
      });
    } else {
      audio.pause();
      btn.textContent = "🔇";
    }
  });

  document.body.appendChild(btn);
                  }
