/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");

  // Update toggle icon
  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";

  btn.style.position = "fixed";
  btn.style.top = "20px";
  btn.style.right = "20px";
  btn.style.zIndex = "9999";

  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });

  document.body.appendChild(btn);
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();

  // Set music source
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
    audio.volume = 0; // start silent
  }

  // Create music toggle
  createMusicToggle(audio);

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

  // Try autoplay with fallback
  tryAutoPlay(audio);

  // Start animations immediately
  buildTimeline(rendered);
});

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered) {
  const tl = gsap.timeline();

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    comp.animate(tl, el, CONFIG);

    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  deferredExits.forEach((fn) => fn());

  // Replay button
  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => tl.restart());
  }
}

// ── Music Helpers ────────────────────────────────────────────────
function tryAutoPlay(audio) {
  if (!audio) return;

  audio.muted = true;

  audio.play()
    .then(() => {
      fadeInAudio(audio, 0.8, 1500);
      audio.muted = false;
    })
    .catch(() => {
      const startOnInteraction = () => {
        audio.play().then(() => {
          fadeInAudio(audio, 0.8, 1500);
        }).catch(() => {});
        document.removeEventListener("click", startOnInteraction);
      };
      document.addEventListener("click", startOnInteraction, { once: true });
    });
}

function fadeInAudio(audio, targetVolume = 1, duration = 1000) {
  const steps = 20;
  const stepTime = duration / steps;
  let currentStep = 0;

  const fade = setInterval(() => {
    currentStep++;
    audio.volume = Math.min(targetVolume, (currentStep / steps) * targetVolume);
    if (currentStep >= steps) clearInterval(fade);
  }, stepTime);
}

function createMusicToggle(audio) {
  if (!audio) return;

  const btn = document.createElement("button");
  btn.id = "music-toggle";
  btn.textContent = "🔊";
  btn.title = "Toggle music";

  btn.style.position = "fixed";
  btn.style.bottom = "20px";
  btn.style.right = "20px";
  btn.style.zIndex = "9999";

  btn.addEventListener("click", () => {
    if (audio.paused) {
      audio.play().then(() => {
        fadeInAudio(audio, 0.8, 800);
        btn.textContent = "🔊";
      });
    } else {
      audio.pause();
      btn.textContent = "🔇";
    }
  });

  document.body.appendChild(btn);
}
